//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.EditTrackings = new HashSet<EditTracking>();
        }
    
        public int Id { get; set; }
        public string AssetTag { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EditTracking> EditTrackings { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
    }
}
